# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c05b35a6cc9a1399f8e1b16cccb5e32c9773f1a58d24a1d9dadc267622e4126e829690269725fed3247e5c41ac8c80a9d1938308ca320eba33e85034f1892f

test:
  secret_key_base: 59d36643e928914cccf09fb00a4cd6d5112e4f02a9b0bb7162af2e7af12cbd5304452a5d5578d415d1f08609ce1aa81e18209d95384462237d087113ca0edb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
